/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./theme/components/Badge.vue')['default']
    CloudinaryImg: typeof import('./theme/components/CloudinaryImg.vue')['default']
    Contributors: typeof import('./theme/components/Contributors.vue')['default']
    CopyRight: typeof import('./theme/components/CopyRight.vue')['default']
    CustomLink: typeof import('./theme/components/CustomLink.vue')['default']
    DemoContainer: typeof import('./theme/components/DemoContainer.vue')['default']
    HomeContributors: typeof import('./theme/components/HomeContributors.vue')['default']
    Iframe: typeof import('./theme/components/Iframe.vue')['default']
    NavCard: typeof import('./theme/components/NavCard.vue')['default']
    PageInfo: typeof import('./theme/components/PageInfo.vue')['default']
    VideoLink: typeof import('./theme/components/VideoLink.vue')['default']
  }
}
